In [9]:
pip install pandas

Requirement already satisfied: pandas in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [11]:
import pandas as pd

In [ ]:
pip install openpyxl

In [12]:
fdata=pd.read_excel(r"D:\Downloads\order_items.xlsx")
fdata

,order_id,item_id,product_id,quantity,list_price,discount,Total Price,product_name
0,1364,2,155,2,11999.99,0.10,23999.88,Trek Domane SLR 9 Disc - 2018
1,1541,1,155,2,11999.99,0.10,23999.88,Trek Domane SLR 9 Disc - 2018
2,1570,1,155,1,11999.99,0.07,11999.92,Trek Domane SLR 9 Disc - 2018
3,1355,3,149,1,7499.99,0.20,7499.79,Trek Domane SLR 8 Disc - 2018
4,1439,4,149,1,7499.99,0.05,7499.94,Trek Domane SLR 8 Disc - 2018
...,...,...,...,...,...,...,...,...
4717,1425,2,263,1,89.99,0.07,89.92,Strider Classic 12 Balance Bike - 2018
4718,1439,2,263,1,89.99,0.20,89.79,Strider Classic 12 Balance Bike - 2018
4719,1462,1,263,1,89.99,0.20,89.79,Strider Classic 12 Balance Bike - 2018
4720,1520,4,263,2,89.99,0.10,179.88,Strider Classic 12 Balance Bike - 2018
4721,1573,5,263,2,89.99,0.10,179.88,Strider Classic 12 Balance Bike - 2018

In [13]:
fdata1=pd.read_excel(r"D:\Downloads\orders.xlsx")
fdata1

,order_id,customer_id,order_status,order_date,required_date,shipped_date,store_id,staff_id
0,1,259,4,2016-01-01,2016-01-03,2016-01-03,1,2
1,2,1212,4,2016-01-01,2016-01-04,2016-01-03,2,6
2,3,523,4,2016-01-02,2016-01-05,2016-01-03,2,7
3,4,175,4,2016-01-03,2016-01-04,2016-01-05,1,3
4,5,1324,4,2016-01-03,2016-01-06,2016-01-06,2,6
...,...,...,...,...,...,...,...,...
1610,1611,6,3,2018-09-06,2018-09-06,NaT,2,7
1611,1612,3,3,2018-10-21,2018-10-21,NaT,1,3
1612,1613,1,3,2018-11-18,2018-11-18,NaT,2,6
1613,1614,135,3,2018-11-28,2018-11-28,NaT,3,8
1614,1615,136,3,2018-12-28,2018-12-28,NaT,3,8

In [14]:
fdata2=pd.read_excel(r"D:\Downloads\products.xlsx")
fdata2

    Row Labels  Sum of Total Price
0            1           102057.59
1            2           100584.30
2            3           415128.84
3            4            55268.07
4            5           163380.24
5            6           627272.56
6            7           656996.56
7  Grand Total          2120688.16

In [15]:
fdata3=pd.read_excel(r"D:\Downloads\customers.xlsx")
fdata3

,customer_id,first_name,last_name,phone,email,street,city,state,zip_code
0,1,Debra,Burks,NaN,debra.burks@yahoo.com,9273 Thorne Ave.,Orchard Park,NY,14127
1,2,Kasha,Todd,NaN,kasha.todd@yahoo.com,910 Vine Street,Campbell,CA,95008
2,3,Tameka,Fisher,NaN,tameka.fisher@aol.com,769C Honey Creek St.,Redondo Beach,CA,90278
3,4,Daryl,Spence,NaN,daryl.spence@aol.com,988 Pearl Lane,Uniondale,NY,11553
4,5,Charolette,Rice,(916) 381-6003,charolette.rice@msn.com,107 River Dr.,Sacramento,CA,95820
...,...,...,...,...,...,...,...,...,...
1440,1441,Jamaal,Morrison,NaN,jamaal.morrison@msn.com,796 SE. Nut Swamp St.,Staten Island,NY,10301
1441,1442,Cassie,Cline,NaN,cassie.cline@gmail.com,947 Lafayette Drive,Brooklyn,NY,11201
1442,1443,Lezlie,Lamb,NaN,lezlie.lamb@gmail.com,401 Brandywine Street,Central Islip,NY,11722
1443,1444,Ivette,Estes,NaN,ivette.estes@gmail.com,88 N. Canterbury Ave.,Canandaigua,NY,14424
1444,1445,Ester,Acevedo,NaN,ester.acevedo@gmail.com,671 Miles Court,San Lorenzo,CA,94580

In [ ]:
df=pd.DataFrame(fdata3)
df

In [16]:
fdata.info()
fdata1.info()
fdata3.info()

<class 'pandas.DataFrame'>
RangeIndex: 4722 entries, 0 to 4721
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      4722 non-null   int64
 1   item_id       4722 non-null   int64
 2   product_id    4722 non-null   int64
 3   quantity      4722 non-null   int64
 4   list_price    4722 non-null   float64
 5   discount      4722 non-null   float64
 6   Total Price   4722 non-null   float64
 7   product_name  4722 non-null   str
dtypes: float64(3), int64(4), str(1)
memory usage: 295.3 KB
<class 'pandas.DataFrame'>
RangeIndex: 1615 entries, 0 to 1614
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       1615 non-null   int64
 1   customer_id    1615 non-null   int64
 2   order_status   1615 non-null   int64
 3   order_date     1615 non-null   datetime64[us]
 4   required_date  1615 non-null   datetime64[us]
 5   shipped_date   1445 non-null   datetime64[us]
 6   store_id       1615 non-null   int64
 7   staff_id       1615 non-null   int64
dtypes: datetime64[us](3), int64(5)
memory usage: 101.1 KB
<class 'pandas.DataFrame'>
RangeIndex: 1445 entries, 0 to 1444
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  1445 non-null   int64
 1   first_name   1445 non-null   str
 2   last_name    1445 non-null   str
 3   phone        178 non-null    str
 4   email        1445 non-null   str
 5   street       1445 non-null   str
 6   city         1445 non-null   str
 7   state        1445 non-null   str
 8   zip_code     1445 non-null   int64
dtypes: int64(2), str(7)
memory usage: 101.7 KB

In [17]:
fdata.describe(include='all')
fdata1.describe(include='all')
fdata3.describe()

       customer_id      zip_code
count  1445.000000   1445.000000
mean    723.000000  34200.015225
std     417.279882  34733.933551
min       1.000000  10002.000000
25%     362.000000  11419.000000
50%     723.000000  11967.000000
75%    1084.000000  76110.000000
max    1445.000000  95993.000000

In [18]:
fdata.value_counts()

order_id  item_id  product_id  quantity  list_price  discount  Total Price  product_name
1364      2        155         2         11999.99    0.10      23999.88     Trek Domane SLR 9 Disc - 2018             1
1541      1        155         2         11999.99    0.10      23999.88     Trek Domane SLR 9 Disc - 2018             1
1570      1        155         1         11999.99    0.07      11999.92     Trek Domane SLR 9 Disc - 2018             1
1355      3        149         1         7499.99     0.20      7499.79      Trek Domane SLR 8 Disc - 2018             1
1439      4        149         1         7499.99     0.05      7499.94      Trek Domane SLR 8 Disc - 2018             1
                                                                                                                     ..
1425      2        263         1         89.99       0.07      89.92        Strider Classic 12 Balance Bike - 2018    1
1439      2        263         1         89.99       0.20      89.79        Strider Classic 12 Balance Bike - 2018    1
1462      1        263         1         89.99       0.20      89.79        Strider Classic 12 Balance Bike - 2018    1
1520      4        263         2         89.99       0.10      179.88       Strider Classic 12 Balance Bike - 2018    1
1573      5        263         2         89.99       0.10      179.88       Strider Classic 12 Balance Bike - 2018    1
Name: count, Length: 4722, dtype: int64

In [19]:
t3=fdata["total_amount"] = (fdata["quantity"] * fdata["list_price"]) - fdata["discount"]
t3

0       23999.88
1       23999.88
2       11999.92
3        7499.79
4        7499.94
          ...
4717       89.92
4718       89.79
4719       89.79
4720      179.88
4721      179.88
Length: 4722, dtype: float64

In [20]:
tsd=fdata1["order_date"] = pd.to_datetime(fdata1["order_date"])
tsd

0      2016-01-01
1      2016-01-01
2      2016-01-02
3      2016-01-03
4      2016-01-03
          ...
1610   2018-09-06
1611   2018-10-21
1612   2018-11-18
1613   2018-11-28
1614   2018-12-28
Name: order_date, Length: 1615, dtype: datetime64[us]

In [21]:
rfm = fdata.merge(fdata1, on="order_id")
rfm

,order_id,item_id,product_id,quantity,list_price,discount,Total Price,product_name,total_amount,customer_id,order_status,order_date,required_date,shipped_date,store_id,staff_id
0,1364,2,155,2,11999.99,0.10,23999.88,Trek Domane SLR 9 Disc - 2018,23999.88,122,4,2018-01-25,2018-01-28,2018-01-28,2,6
1,1541,1,155,2,11999.99,0.10,23999.88,Trek Domane SLR 9 Disc - 2018,23999.88,10,2,2018-04-16,2018-04-16,NaT,2,7
2,1570,1,155,1,11999.99,0.07,11999.92,Trek Domane SLR 9 Disc - 2018,11999.92,54,2,2018-04-22,2018-04-22,NaT,2,7
3,1355,3,149,1,7499.99,0.20,7499.79,Trek Domane SLR 8 Disc - 2018,7499.79,1010,4,2018-01-19,2018-01-21,2018-01-20,2,7
4,1439,4,149,1,7499.99,0.05,7499.94,Trek Domane SLR 8 Disc - 2018,7499.94,463,4,2018-03-15,2018-03-16,2018-03-17,2,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4717,1425,2,263,1,89.99,0.07,89.92,Strider Classic 12 Balance Bike - 2018,89.92,126,4,2018-03-07,2018-03-09,2018-03-09,2,6
4718,1439,2,263,1,89.99,0.20,89.79,Strider Classic 12 Balance Bike - 2018,89.79,463,4,2018-03-15,2018-03-16,2018-03-17,2,7
4719,1462,1,263,1,89.99,0.20,89.79,Strider Classic 12 Balance Bike - 2018,89.79,1101,4,2018-03-22,2018-03-24,2018-03-24,2,6
4720,1520,4,263,2,89.99,0.10,179.88,Strider Classic 12 Balance Bike - 2018,179.88,66,2,2018-04-11,2018-04-11,NaT,3,8
4721,1573,5,263,2,89.99,0.10,179.88,Strider Classic 12 Balance Bike - 2018,179.88,24,2,2018-04-23,2018-04-23,NaT,1,2

In [22]:
snapshot_date = fdata1["order_date"].max() + pd.Timedelta(days=1)

rfm_data = rfm.groupby("customer_id").agg({
    "order_date": lambda x: (snapshot_date - x.max()).days,
    "order_id": "count",
    "total_amount": "sum"
})

rfm_data.columns = ["Recency", "Frequency", "Monetary"]

rfm_data.head()

             Recency  Frequency  Monetary
customer_id
1                 41         11  30644.78
2                264         10  21652.87
3                 69         13  26248.66
4                255          9  24197.81
5                256          8  19442.01

In [25]:
rfm_data.to_excel(r"c:\users\ELCOT\Downloads\customer_segments.xlsx", index=False)

OSError: Cannot save file into a non-existent directory: 'c:\users\ELCOT\Downloads'

In [26]:
import os
print(os.getcwd())

C:\Users\ELCOT

In [27]:
import os
print(os.listdir("c:\\Users\\ELCOT"))

['-1.14-windows.xml', '.idlerc', '.ipynb_checkpoints', '.ipython', '.jupyter', '.ms-ad', 'AppData', 'Application Data', 'Contacts', 'Cookies', 'customer_segments.xlsx', 'Desktop', 'Documents', 'Favorites', 'final project', 'fproject', 'fproject.ipynb', 'Links', 'Local Settings', 'Microsoft', 'My Documents', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{ab72997f-dcec-11f0-a504-08f97eb60b90}.TM.blf', 'NTUSER.DAT{ab72997f-dcec-11f0-a504-08f97eb60b90}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{ab72997f-dcec-11f0-a504-08f97eb60b90}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'PrintHood', 'Recent', 'Saved Games', 'Searches', 'SendTo', 'Start Menu', 'Templates', 'Untitled.ipynb', 'Untitled1.ipynb', 'Untitled2.ipynb', 'Untitled3.ipynb', 'Untitled4.ipynb', 'Untitled5.ipynb', 'Untitled6.ipynb', 'Untitled7.ipynb']

In [28]:
rfm_data.to_excel(r"C:\Users\ELCOT\Desktop\customer_segments.xlsx", index=False)
print("Saved Successfully!")

Saved Successfully!